--CREATING THE TABLES 
--CREATED THE CUSTOMER TABLE  
CREATE TABLE DBO.CUSTOMERS (
    CUSTOMERID INT PRIMARY KEY,
    CUSTOMERNAME VARCHAR(100) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    SIGNUPDATE DATE NOT NULL
)

--CREATING THE PRODUCTS TABLE  
CREATE TABLE DBO.PRODUCTS (
    PRODUCTID INT PRIMARY KEY,
    PRODUCTNAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL
)

--CREATING THE ORDERS TABLE  
CREATE TABLE DBO.ORDERS (
    ORDERID INT PRIMARY KEY,
    CUSTOMERID INT NOT NULL,
    ORDERDATE DATE NOT NULL,

    CONSTRAINT FK_ORDERS_CUSTOMERS
        FOREIGN KEY (CUSTOMERID)
        REFERENCES DBO.CUSTOMERS(CUSTOMERID)
)

--CREATING THE ORDERITEMS TABLE  
CREATE TABLE DBO.ORDERITEMS (
    ORDERITEMID INT PRIMARY KEY,
    ORDERID INT NOT NULL,
    PRODUCTID INT NOT NULL,
    QUANTITY INT NOT NULL,

    CONSTRAINT FK_ORDERITEMS_ORDERS
        FOREIGN KEY (ORDERID)
        REFERENCES DBO.ORDERS(ORDERID),

    CONSTRAINT FK_ORDERITEMS_PRODUCTS
        FOREIGN KEY (PRODUCTID)
        REFERENCES DBO.PRODUCTS(PRODUCTID)
)
