USE RETAIL_SALES
GO

--FETCHING ALL DATA FROM ALL TABLES
SELECT*FROM DBO.CUSTOMERS
SELECT*FROM DBO.ORDERITEMS
SELECT*FROM DBO.ORDERS
SELECT*FROM DBO.PRODUCTS

--  VIEW ALL PRODUCTS, MOST EXPENSIVE FIRST
SELECT PRODUCTNAME, CATEGORY, PRICE
      FROM DBO.PRODUCTS
         ORDER BY PRICE DESC

--FIND CUSTOMERS FROM DELHI
SELECT * FROM DBO.CUSTOMERS  WHERE CITY='DELHI'

--FIND PRODUCTS COSTING MORE THAN ₹1,000
SELECT PRODUCTNAME, CATEGORY, PRICE FROM DBO.PRODUCTS
      WHERE PRICE > 1000
         ORDER BY PRICE DESC

--COUNT TOTAL CUSTOMERS
SELECT COUNT(*) AS TOTALCUSTOMERS FROM DBO.CUSTOMERS

--COUNT PRODUCTS IN EVERY CATEGORY
SELECT CATEGORY, COUNT(*) AS PRODUCTCOUNT FROM DBO.PRODUCTS
     GROUP BY CATEGORY
        ORDER BY PRODUCTCOUNT DESC

--VIEW EVERY ORDER WITH CUSTOMER NAME AND CITY
SELECT O.ORDERID,C.CUSTOMERNAME,C.CITY,O.ORDERDATE
     FROM DBO.ORDERS AS O
     JOIN DBO.CUSTOMERS AS C
     ON O.CUSTOMERID = C.CUSTOMERID
       ORDER BY O.ORDERDATE

--VIEW DETAILED ORDER ITEMS WITH PRODUCT DETAILS
SELECT OI.ORDERITEMID,OI.ORDERID,P.PRODUCTNAME,P.CATEGORY,P.PRICE,
       OI.QUANTITY,(P.PRICE * OI.QUANTITY) AS ITEMTOTAL
       FROM DBO.ORDERITEMS AS OI
       JOIN DBO.PRODUCTS AS P
       ON OI.PRODUCTID = P.PRODUCTID
         ORDER BY OI.ORDERID

--SHOW EACH ORDER WITH ITS TOTAL BILL AMOUNT
SELECT O.ORDERID,C.CUSTOMERNAME,O.ORDERDATE, SUM(P.PRICE * OI.QUANTITY) AS ORDERTOTAL
       FROM DBO.ORDERS AS O
       JOIN DBO.CUSTOMERS AS C
       ON O.CUSTOMERID = C.CUSTOMERID
       JOIN DBO.ORDERITEMS AS OI
       ON O.ORDERID = OI.ORDERID
       JOIN DBO.PRODUCTS AS P
       ON OI.PRODUCTID = P.PRODUCTID
       GROUP BY O.ORDERID, C.CUSTOMERNAME, O.ORDERDATE
       ORDER BY ORDERTOTAL DESC

--CALCULATE TOTAL REVENUE OF THE STORE
SELECT SUM(P.PRICE * OI.QUANTITY) AS TOTALREVENUE
       FROM DBO.ORDERITEMS AS OI
       JOIN DBO.PRODUCTS AS P
       ON OI.PRODUCTID = P.PRODUCTID

--CALCULATE REVENUE BY PRODUCT CATEGORY
SELECT P.CATEGORY,SUM(P.PRICE * OI.QUANTITY) AS CATEGORYREVENUE
       FROM DBO.ORDERITEMS AS OI
       JOIN DBO.PRODUCTS AS P
       ON OI.PRODUCTID = P.PRODUCTID
       GROUP BY P.CATEGORY
       ORDER BY CATEGORYREVENUE DESC

--FIND THE TOP 5 BEST-SELLING PRODUCTS BY QUANTITY
SELECT TOP (5) P.PRODUCTNAME,SUM(OI.QUANTITY) AS TOTALQUANTITYSOLD
       FROM DBO.ORDERITEMS AS OI
       JOIN DBO.PRODUCTS AS P
       ON OI.PRODUCTID = P.PRODUCTID
       GROUP BY P.PRODUCTNAME
       ORDER BY TOTALQUANTITYSOLD DESC

--FIND THE TOP 5 PRODUCTS BY REVENUE
SELECT TOP 5 P.PRODUCTNAME,SUM(P.PRICE * OI.QUANTITY) AS PRODUCTREVENUE
       FROM DBO.ORDERITEMS AS OI
       JOIN DBO.PRODUCTS AS P
       ON OI.PRODUCTID = P.PRODUCTID
       GROUP BY P.PRODUCTNAME
       ORDER BY PRODUCTREVENUE DESC

--FIND PRODUCTS THAT WERE NEVER ORDERED
SELECT P.PRODUCTID,P.PRODUCTNAME,P.CATEGORY
       FROM DBO.PRODUCTS AS P
       LEFT JOIN DBO.ORDERITEMS AS OI
       ON P.PRODUCTID = OI.PRODUCTID
       WHERE OI.PRODUCTID IS NULL

--FIND THE TOP 5 CUSTOMERS BY TOTAL SPENDING
SELECT TOP 5 C.CUSTOMERNAME,C.CITY,SUM(P.PRICE * OI.QUANTITY) AS TOTALSPENT
       FROM DBO.CUSTOMERS AS C
       JOIN DBO.ORDERS AS O
       ON C.CUSTOMERID = O.CUSTOMERID
       JOIN DBO.ORDERITEMS AS OI
       ON O.ORDERID = OI.ORDERID
       JOIN DBO.PRODUCTS AS P
       ON OI.PRODUCTID = P.PRODUCTID
       GROUP BY C.CUSTOMERNAME, C.CITY
       ORDER BY TOTALSPENT DESC

--COUNT ORDERS PLACED BY EACH CUSTOMER
SELECT C.CUSTOMERNAME,COUNT(O.ORDERID) AS NUMBEROFORDERS
     FROM DBO.CUSTOMERS AS C
     LEFT JOIN DBO.ORDERS AS O
     ON C.CUSTOMERID = O.CUSTOMERID
     GROUP BY C.CUSTOMERNAME
     ORDER BY NUMBEROFORDERS DESC

--FIND REVENUE GENERATED FROM EACH CITY
SELECT C.CITY,SUM(P.PRICE * OI.QUANTITY) AS CITYREVENUE
     FROM DBO.CUSTOMERS AS C
     JOIN DBO.ORDERS AS O
     ON C.CUSTOMERID = O.CUSTOMERID
     JOIN DBO.ORDERITEMS AS OI
     ON O.ORDERID = OI.ORDERID
     JOIN DBO.PRODUCTS AS P
     ON OI.PRODUCTID = P.PRODUCTID
     GROUP BY C.CITY
     ORDER BY CITYREVENUE DESC

--FIND CITIES HAVING SALES GREATER THAN ₹3,000
SELECT C.CITY,SUM(P.PRICE * OI.QUANTITY) AS CITYREVENUE
     FROM DBO.CUSTOMERS AS C
     JOIN DBO.ORDERS AS O
     ON C.CUSTOMERID = O.CUSTOMERID
     JOIN DBO.ORDERITEMS AS OI
     ON O.ORDERID = OI.ORDERID
     JOIN DBO.PRODUCTS AS P
     ON OI.PRODUCTID = P.PRODUCTID
     GROUP BY C.CITY
     HAVING SUM(P.PRICE * OI.QUANTITY) > 3000
     ORDER BY CITYREVENUE DESC

--FIND MONTHLY SALES REVENUE
SELECT FORMAT(O.ORDERDATE, 'YYYY-MM') AS SALESMONTH,SUM(P.PRICE * OI.QUANTITY) AS MONTHLYREVENUE
     FROM DBO.ORDERS AS O
     JOIN DBO.ORDERITEMS AS OI
     ON O.ORDERID = OI.ORDERID
     JOIN DBO.PRODUCTS AS P
     ON OI.PRODUCTID = P.PRODUCTID
     GROUP BY FORMAT(O.ORDERDATE, 'YYYY-MM')
     ORDER BY SALESMONTH

--FIND TOTAL ORDERS FOR EACH MONTH
SELECT FORMAT(ORDERDATE, 'YYYY-MM') AS ORDERMONTH,COUNT(ORDERID) AS TOTALORDERS
     FROM DBO.ORDERS
     GROUP BY FORMAT(ORDERDATE, 'YYYY-MM')
     ORDER BY ORDERMONTH

--FIND SALES BY DAY
SELECT O.ORDERDATE,SUM(P.PRICE * OI.QUANTITY) AS DAILYREVENUE
     FROM DBO.ORDERS AS O
     JOIN DBO.ORDERITEMS AS OI
     ON O.ORDERID = OI.ORDERID
     JOIN DBO.PRODUCTS AS P
     ON OI.PRODUCTID = P.PRODUCTID
     GROUP BY O.ORDERDATE
     ORDER BY O.ORDERDATE

--CLASSIFY PRODUCTS BY PRICE
SELECT PRODUCTNAME,PRICE,
    CASE
        WHEN PRICE >= 1500 THEN 'HIGH PRICE'
        WHEN PRICE >= 500 THEN 'MEDIUM PRICE'
        ELSE 'LOW PRICE'
    END AS PRICECATEGORY
      FROM DBO.PRODUCTS
          ORDER BY PRICE DESC

--FIND PRODUCTS PRICED ABOVE THE AVERAGE PRODUCT PRICE
SELECT PRODUCTNAME,CATEGORY,PRICE
     FROM DBO.PRODUCTS
     WHERE PRICE > (
       SELECT AVG(PRICE)
        FROM DBO.PRODUCTS
     )
       ORDER BY PRICE DESC

--USE A CTE TO CALCULATE EVERY CUSTOMER'S TOTAL SPENDING
WITH CUSTOMERSPENDING AS (
    SELECT
        C.CUSTOMERID,
        C.CUSTOMERNAME,
        SUM(P.PRICE * OI.QUANTITY) AS TOTALSPENT
    FROM DBO.CUSTOMERS AS C
    JOIN DBO.ORDERS AS O
        ON C.CUSTOMERID = O.CUSTOMERID
    JOIN DBO.ORDERITEMS AS OI
        ON O.ORDERID = OI.ORDERID
    JOIN DBO.PRODUCTS AS P
        ON OI.PRODUCTID = P.PRODUCTID
    GROUP BY C.CUSTOMERID, C.CUSTOMERNAME
)
SELECT
    CUSTOMERNAME,
    TOTALSPENT
FROM CUSTOMERSPENDING
ORDER BY TOTALSPENT DESC

--RANK CUSTOMERS BY TOTAL SPENDING
WITH CUSTOMERSPENDING AS (
    SELECT
        C.CUSTOMERNAME,
        SUM(P.PRICE * OI.QUANTITY) AS TOTALSPENT
    FROM DBO.CUSTOMERS AS C
    JOIN DBO.ORDERS AS O
        ON C.CUSTOMERID = O.CUSTOMERID
    JOIN DBO.ORDERITEMS AS OI
        ON O.ORDERID = OI.ORDERID
    JOIN DBO.PRODUCTS AS P
        ON OI.PRODUCTID = P.PRODUCTID
    GROUP BY C.CUSTOMERNAME
)
SELECT
    CUSTOMERNAME,
    TOTALSPENT,
    RANK() OVER (ORDER BY TOTALSPENT DESC) AS SPENDINGRANK
FROM CUSTOMERSPENDING

--RANK PRODUCTS BY REVENUE INSIDE EACH CATEGORY
WITH PRODUCTREVENUE AS (
    SELECT
        P.CATEGORY,
        P.PRODUCTNAME,
        SUM(P.PRICE * OI.QUANTITY) AS REVENUE
    FROM DBO.PRODUCTS AS P
    JOIN DBO.ORDERITEMS AS OI
        ON P.PRODUCTID = OI.PRODUCTID
    GROUP BY P.CATEGORY, P.PRODUCTNAME
)
SELECT CATEGORY,PRODUCTNAME,REVENUE,
    RANK() OVER (
        PARTITION BY CATEGORY
        ORDER BY REVENUE DESC
    ) AS RANKINCATEGORY
FROM PRODUCTREVENUE
ORDER BY CATEGORY, RANKINCATEGORY

--FIND THE HIGHEST-VALUE ORDER
SELECT TOP 1 O.ORDERID,C.CUSTOMERNAME,SUM(P.PRICE * OI.QUANTITY) AS ORDERTOTAL
     FROM DBO.ORDERS AS O
     JOIN DBO.CUSTOMERS AS C
     ON O.CUSTOMERID = C.CUSTOMERID
     JOIN DBO.ORDERITEMS AS OI
     ON O.ORDERID = OI.ORDERID
     JOIN DBO.PRODUCTS AS P
     ON OI.PRODUCTID = P.PRODUCTID
     GROUP BY O.ORDERID, C.CUSTOMERNAME
     ORDER BY ORDERTOTAL DESC

--FIND AVERAGE ORDER VALUE
WITH ORDERTOTALS AS (
    SELECT
        O.ORDERID,
        SUM(P.PRICE * OI.QUANTITY) AS ORDERTOTAL
    FROM DBO.ORDERS AS O
    JOIN DBO.ORDERITEMS AS OI
        ON O.ORDERID = OI.ORDERID
    JOIN DBO.PRODUCTS AS P
        ON OI.PRODUCTID = P.PRODUCTID
    GROUP BY O.ORDERID
)
SELECT
    AVG(ORDERTOTAL) AS AVERAGEORDERVALUE
FROM ORDERTOTALS
